root = "."
tmp_dir = "tmp" 

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "APP_ENV=development APP_PORT=8080 ./tmp/main" 
  include_ext = ["go", "tpl", "tmpl", "html", "env"] 
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", ".git"]  
  stop_on_error = true
  log = "air_errors.log" 

[log]
  time = true
  level = "info" 

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true

[watch]
  poll = true
  poll_interval = 500
  